# Layers and Matrix Multiplication

This notebook extends forward propagation to:
- Multiple samples (batch processing)
- Multiple layers

We use matrix multiplication for efficiency.

Code

In [2]:
import numpy as np

inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2.0, 3.0, 0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

print("Layer 1 output:")
print(layer1_outputs)

Layer 1 output:
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


Second Layer

In [3]:
weights2 = [
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, 0.13]
]

biases2 = [-1, 2, -0.5]

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print("Layer 2 output:")
print(layer2_outputs)

Layer 2 output:
[[ 0.5031  -1.04185 -1.41865]
 [ 0.2434  -2.7332  -5.7113 ]
 [-0.99314  1.41254 -0.34979]]
