# Activation Functions: ReLU and Softmax

Activation functions introduce non-linearity.

We implement:
- ReLU (Rectified Linear Unit)
- Softmax (for probabilities)

ReLU

In [2]:

import numpy as np

inputs = [0, 2, -1, 3.3, -2.7, 1.1]

outputs = np.maximum(0, inputs)
print("ReLU output:", outputs)

ReLU output: [0.  2.  0.  3.3 0.  1.1]


Softmax

In [3]:
inputs = [
    [1, 2, 3],
    [2, 5, -1],
    [-1, 2, 3]
]

exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

print("Softmax probabilities:")
print(probabilities)
print("Sum per sample:", np.sum(probabilities, axis=1))

Softmax probabilities:
[[0.09003057 0.24472847 0.66524096]
 [0.04731416 0.95033021 0.00235563]
 [0.01321289 0.26538793 0.72139918]]
Sum per sample: [1. 1. 1.]
