# Backpropagation: Gradient-Based Learning

Backpropagation computes gradients using the chain rule.

Goal:
- Compute gradients of loss w.r.t weights and biases
- Update parameters to minimize loss

Code

In [1]:
import numpy as np 

# Initial inpusts  ( We have about four inputs )
inputs = np.array([1, 2, 3, 4]) # converting them to matrix

# Initial weights and biases associated with the 3 neurons
weights = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

biases = np.array([0.1, 0.2, 0.3])
# Learning rate which is a hyperparameter
learning_rate = 0.001 # is the standard value 

# Create a function for relu activation and it's derivative 
def relu(x): # Accepts only one parameter 
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 1, 1, 0)

# Training loop 
for iteration in range(200): 
    # Forward pass
    # Applying the basic formula to calculate the output (z)
    z = np.dot(weights, inputs) + biases
    # Then apply the activation relu (a)
    a = relu(z) # will accept the ouput as it's parameter
    # Final output (y) of the forward pass and compress to single value
    y = np.sum(a)

    # calculate the loss the square of the ouput of the f pass
    loss = y ** 2


    # Backward pass
    # derivative of the loss with respect to the output (y)
    dL_dy = 2 * y

    # derivative of output (y) with respect to the relu output(a)
    dy_da = np.ones_like(a)

    # derivative of loss wrt to output of relu (a)
    dL_da = dL_dy * dy_da

    # derivative of the output of the relu (a) wrt to output of neuron (z)
    da_dz = relu_derivative(z)

    # derivative of the loss wrt to output of neuron
    dL_dz = dL_da * da_dz

    # derivative LOSS wrt to the weights
    dL_dW = np.outer(dL_dy, inputs)
    dL_db = dL_dz

    # Update the weights and biases 
    weights -= learning_rate * dL_dW
    biases -= learning_rate * dL_db

    # Print the loss for every other 20 iteration 
    if iteration % 20 == 0:
        print(f"Iteration {iteration}, Loss: {loss}")


# Print the final updated weights and biases 
print("Final weight:\n", weights)
print("Final biases:\n", biases)
    






Iteration 0, Loss: 466.56000000000006
Iteration 20, Loss: 5.324530697648097
Iteration 40, Loss: 0.42217747008387807
Iteration 60, Loss: 0.035531144514264014
Iteration 80, Loss: 0.002990359078713253
Iteration 100, Loss: 0.000251673497769053
Iteration 120, Loss: 2.1181252087815377e-05
Iteration 140, Loss: 1.782648725370902e-06
Iteration 160, Loss: 1.5003062448293397e-07
Iteration 180, Loss: 1.2626822077964556e-08
Final weight:
 [[-0.26552778 -0.53105556 -0.79658334 -1.06211112]
 [ 0.13447222 -0.13105556 -0.39658334 -0.66211112]
 [ 0.53447222  0.26894444  0.00341666 -0.26211112]]
Final biases:
 [ 0.0216352  -0.0118978  -0.03413396]


GRADIENT OF THE LOSS WITH RESPECT TO WEIGHTS

In [2]:
import numpy as np 
# Passing the gradient from the next layer
# Going to incremental gradients

dvalues = np.array([
    [1., 1., 1.],
    [2., 2., 2.],
    [3., 3., 3.]
])

# We have set's of inputs : Samples
inputs = np.array([
    [1, 2, 3, 2.5],
    [2., 5., -1, 2],
    [-1.5, 2.7, 3.3, -0.8]
])

# find the dot product between the inputs and derivative of the loss
dweights = np.dot(inputs.T, dvalues)
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


GRADIENT OF THE LOSS WITH RESPECT TO THE INPUTS 




In [9]:
import numpy as np
# Passed-in gradient from the next layer
# Going to use an array gradient values

dvalues = np.array([
    [1., 1., 1.],
    [2., 2., 2.],
    [3., 3., 3]
])

# We have 3 sets of weights and keep the right dimention
weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])
 # Apply dot product of the gradient and the weights as the input
dinputs = np.dot(dvalues, weights)
print(dinputs)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


GRADIENT OF THE LOSS WITH RESPECT TO BIASES

In [10]:
import numpy as np
# Passed-in the gradient in the next layer
# for incremental purposes
dvalues = np.array([
    [1., 1., 1.],
    [2., 2., 2],
    [3., 3., 3.]
])
# Since we have three neurons there's a bias for each
biases = np.array([2, 3, 0.5])
# dbiases we sum all the colums to get the row vector
dbiases = np.sum(dvalues, axis=0, keepdims=True)
print(dbiases)

[[6. 6. 6.]]


BACKWARD METHOD THAT SHOULD BE ADDED TO THE LAYER-DENSE LAYER

In [3]:
# class layer_Dense

# Backward pass
# def backward(self, dvalues):
# Gradient on the parameters
# self.dweights = np.dot(self.inputs, dvalues)
# self.dbiases = np.sum(dvalues, axis=0, keepdims=True)
# Gradient on the values
# self.inputs = np.dot(dvalues, self.weights.T)

ADDING BACKWARD METHOD TO THE RELU ACTIVATION FUNCTION CLASS


In [4]:
# ReLU activation
# class Activation_ReLU:
# Forward pass
# def forward(self, inputs):
# self.inputs = inputs
# self.ouputs = np.maximum(0, inputs)
# Backward pass
# def backward(self, dvalues):
# since we a copy of the original values and modify those
# let's make a copy of the values first
# self.dinputs  = dvalues.copy()
# Zero gradients where input values are negative 
# self.dinputs[self.inputs <= 0] = 0


LOSS FUNCTION BACKPROPAGATION

In [ ]:
# class Loss_CategoricalCrossentropy(Loss):
#  ...
#  # Backward pass
#  def backward(self, dvalues, y_true):
#  # Number of samples
#  samples = len(dvalues)
#  # Number of labels in every sample
#  # We'll use the first sample to count them
#  labels = len(dvalues[0])
#  # If labels are sparse, turn them into one-hot vector
#  if len(y_true.shape) == 1:
#  y_true = np.eye(labels)[y_true]
#  # Calculate gradient
#  self.dinputs = -y_true / dvalues
#  # Normalize gradient
#  self.dinputs = self.dinputs / samples